# Upgrade system packages, configure locales & NTP, install misc. packages
---

- dynamic_defaults:
    hostvars: '{{ hostvars[inventory_hostname] }}'
    defaults: '{{ miscellaneous_dynamic_defaults }}'
    must_match: true
  tags: [miscellaneous, always]

- include_tasks: setup-upgrade-{{ ansible_pkg_mgr }}.yml
  tags: [miscellaneous, packages, upgrade]

- name: Install extra packages
  ansible.builtin.package:
    name: '{{ extra_packages }}'
    state: present
  become: true
  tags: [miscellaneous, packages]

- block:
    - name: Set swappiness
      ansible.builtin.sysctl:
        name: vm.swappiness
        state: present
        sysctl_set: true
        value: '{{ vm_swappiness|int }}'

    - name: Toggle TCP Selective Acknowledgment
      ansible.builtin.sysctl:
        name: net.ipv4.tcp_sack
        state: present
        sysctl_set: true
        value: '{{ net_tcp_sack|bool|ternary(1, 0) }}'
      changed_when: _tcp_sack is change
      failed_when: _tcp_sack is failure and 'No such file' not in _tcp_sack.msg
      register: _tcp_sack
  become: true
  tags: [miscellaneous, network, sysctl, config]

- block:
    - name: Check Network Manager configuration directory exists
      ansible.builtin.stat:
        path: /etc/NetworkManager/conf.d
      register: _network_manager_config

    - name: Remove default WiFi PowerSafe Configuration
      ansible.builtin.file:
        name: /etc/NetworkManager/conf.d/default-wifi-powersave-on.conf
        state: absent
      notify: restart network manager
      when: _network_manager_config.stat.exists

    - name: Configure WiFi PowerSafe Mode
      ansible.builtin.template:
        src: wifi.powersave.conf.j2
        dest: /etc/NetworkManager/conf.d/ansible-role-miscellaneous-wifi-powersafe.conf
      notify: restart network manager
      when: _network_manager_config.stat.exists
  become: true
  tags: [miscellaneous, network, config]

- include_tasks: setup-locale-{{ ansible_pkg_mgr }}.yml
  tags: [miscellaneous, locale, config]
  when: locale|length > 0

- name: Configure timezone
  ansible.builtin.timezone:
    name: '{{ timezone }}'
  become: true
  tags: [miscellaneous, timezone, config]
  when: timezone|length > 0

- block:
    - name: Install NTP
      ansible.builtin.package:
        name: '{{ ntp_package }}'
        state: present
      tags: packages

    - name: Start NTP service
      ansible.builtin.service:
        name: '{{ ntp_service }}'
        enabled: true
        state: started
      tags: services
  become: true
  tags: [miscellaneous, ntp]

- block:
    - name: Install usefull system tools
      ansible.builtin.package:
        name: '{{ system_tools }}'
        state: present

    - name: Install usefull system administration tools
      ansible.builtin.package:
        name: '{{ system_administration_tools }}'
        state: present
  become: true
  tags: [miscellaneous, packages]

...
