---

- block:
    - name: Set the default locale
      ansible.builtin.debconf:
        name: locales
        question: locales/{{ item.name }}
        value: '{{ item.value }}'
        vtype: '{{ item.type }}'
      loop:
        - name: default_environment_locale
          value: '{{ locale }}'
          type: select
        #- { name: 'locales_to_be_generated',    value: "{{ locale }} {{ locale|split('.')[1] }}", type: 'multiselect' }
      loop_control:
        label: '{{ item.name }} = {{ item.value }}'

    - name: Install locales package
      ansible.builtin.package:
        name: locales
        state: present

    # FIXME https://github.com/ansible/ansible-modules-extras/issues/425
    - name: Generate our locale
      ansible.builtin.locale_gen:
        name: '{{ locale }}'
        state: present
      ignore_errors: true

    - name: Reconfigure the locales and enable our locale
      ansible.builtin.shell: >
        dpkg-reconfigure locales -f noninteractive &&
        update-locale LANG={{ locale }} LC_ALL={{ locale }}
  become: true
  tags: [miscellaneous, locale, config]

...
