---

- name: Set the default locale
  ansible.builtin.command: >
    localedef
    --force
    --inputfile {{ locale.split('.')[0] }}
    --charmap {{ locale.split('.')[1] }} {{ locale }}
  become: true
  # changed_when:  FIXME to implement
  tags: [miscellaneous, locale, config]
  when: locale|length > 0

...
