# FIXME Tnteresting link http://ask.xmodulo.com/install-python3-centos.html
---

- block:
    - name: Install EPEL repository
      package:
        name: epel-release
        state: "{{ yum_epel_repository|bool|ternary('present', 'absent') }}"

    - name: Install package manager tools
      package:
        name: '{{ package_manager_tools }}'
        state: present

    - name: Upgrade the packages
      yum:
        name: '*'
        state: latest
        update_cache: yes
      async: '{{ omit if ansible_check_mode else upgrade_packages_async }}'
      poll: '{{ upgrade_packages_poll }}'
      when: upgrade_packages|bool
  become: yes
  tags: [miscellaneous, packages, upgrade] # FIXME Remove when this is fixed https://github.com/ansible/ansible/issues/30882
