# https://www.linuxtechi.com/enable-epel-repo-centos8-rhel8-server/
---

- block:
    - name: Install EPEL repository
      package:
        name: epel-release
        state: "{{ dnf_epel_repository|bool|ternary('present', 'absent') }}"

    - name: Install package manager tools
      package:
        name: '{{ package_manager_tools }}'
        state: present

    - name: Upgrade the packages
      dnf:
        name: '*'
        state: latest
        update_cache: yes
      async: '{{ omit if ansible_check_mode else upgrade_packages_async }}'
      poll: '{{ upgrade_packages_poll }}'
      when: upgrade_packages|bool
  become: yes
  tags: [miscellaneous, packages, upgrade] # FIXME Remove when this is fixed https://github.com/ansible/ansible/issues/30882
