# https://www.linuxtechi.com/enable-epel-repo-centos8-rhel8-server/
---

- block:
    - name: Install EPEL repository
      ansible.builtin.package:
        name: epel-release
        state: "{{ dnf_epel_repository|bool|ternary('present', 'absent') }}"

    - name: Install package manager tools
      ansible.builtin.package:
        name: '{{ package_manager_tools }}'
        state: present

    - name: Upgrade the packages
      ansible.builtin.dnf:
        name: '*'
        state: latest
        update_cache: true
      async: '{{ omit if ansible_check_mode else upgrade_packages_async }}'
      poll: '{{ upgrade_packages_poll }}'
      when: upgrade_packages|bool
  become: true
  tags: [miscellaneous, packages, upgrade]

...
